<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [BulmaGés] Error al ejecutar bulmasetup
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/bulmages-main/2008-November/index.html" >
   <LINK REL="made" HREF="mailto:bulmages-main%40lists.berlios.de?Subject=Re%3A%20%3D%3Futf-8%3Fb%3FW0J1bG1hR8Opc10%3D%3F%3D%20Error%20al%20ejecutar%20bulmasetup&In-Reply-To=%3Ce62868e0811041142n14c38730y97b629d5ff8ff0f6%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
   <LINK REL="Previous"  HREF="000425.html">
   <LINK REL="Next"  HREF="000254.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[BulmaGés] Error al ejecutar bulmasetup </H1>
    <B>infoaxset axset</B> 
    <A HREF="mailto:bulmages-main%40lists.berlios.de?Subject=Re%3A%20%3D%3Futf-8%3Fb%3FW0J1bG1hR8Opc10%3D%3F%3D%20Error%20al%20ejecutar%20bulmasetup&In-Reply-To=%3Ce62868e0811041142n14c38730y97b629d5ff8ff0f6%40mail.gmail.com%3E"
       TITLE="[BulmaGés] Error al ejecutar bulmasetup">infoaxset en gmail.com
       </A><BR>
    <I>Mar Nov  4 20:42:04 CET 2008</I>
    <P><UL>
        <LI>Mensaje anterior: <A HREF="000425.html">[BulmaGés][BulmaFact y BulmaTPV] Dudas variadas y fallos variados
</A></li>
        <LI>Próximo mensaje: <A HREF="000254.html">[BulmaGés]Error al ejecutar bulmasetup
</A></li>
         <LI> <B>Mensajes ordenados por:</B> 
              <a href="date.html#252">[ fecha ]</a>
              <a href="thread.html#252">[ hilo ]</a>
              <a href="subject.html#252">[ asunto ]</a>
              <a href="author.html#252">[ autor ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Buenos dias a todos

Cuando intento ejecutar bulmasetup me aparece lo siguiente:

$ sudo bulmasetup
Traceback (most recent call last):
  File &quot;/usr/bin/bulmasetup&quot;, line 16, in &lt;module&gt;
    from bulmasetupbase import *
  File &quot;/opt/bulmages/usr/share/bulmages/bulmasetup/bulmasetupbase.py&quot;, line
10, in &lt;module&gt;
    from PyQt4 import QtCore, QtGui
RuntimeError: the sip module supports API v3.0 to v3.6 but the PyQt4.QtCore
module requires API v3.7

Me he dejado algun paquete?
La ultima vez que os consulte tenia los paquetes, lo que se habian instalado
erroneamente.

Agradezco lo rapido de la contestacion anterior

Un saludo
------------ próxima parte ------------
Se ha borrado un adjunto en formato HTML...
URL: &lt;<A HREF="https://lists.berlios.de/pipermail/bulmages-main/attachments/20081104/7b4b9584/attachment.html">https://lists.berlios.de/pipermail/bulmages-main/attachments/20081104/7b4b9584/attachment.html</A>&gt;
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Mensaje anterior: <A HREF="000425.html">[BulmaGés][BulmaFact y BulmaTPV] Dudas variadas y fallos variados
</A></li>
	<LI>Próximo mensaje: <A HREF="000254.html">[BulmaGés]Error al ejecutar bulmasetup
</A></li>
         <LI> <B>Mensajes ordenados por:</B> 
              <a href="date.html#252">[ fecha ]</a>
              <a href="thread.html#252">[ hilo ]</a>
              <a href="subject.html#252">[ asunto ]</a>
              <a href="author.html#252">[ autor ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/bulmages-main">Más información sobre la lista de distribución Bulmages-main </a><br>
</body></html>
